GET http://localhost:3001/api/notes/

###
POST http://localhost:3001/api/notes/ HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###
PUT http://localhost:3001/api/notes/67510af0ed969222448b5228 HTTP/1.1
Content-Type: application/json

{
    "name": "a new note",
    "important": true
}